### PR TITLE
Update docs to suggest the latest version of the driver

### PR DESCRIPTION
**Pull request by walterdolce**
The docs should always be kept up to date and reflect the current state of reality. This PR suggest to use the latest available set of versions of the driver so that users don't get confused when starting out with using the driver.

### CODE REVIEW

**Comment by ncs-alane** [comment]
Hi @walterdolce:

Thanks for your interest in the project! Can you change the version number to 0.4 and point this pull request to the ncs-alane-0.4.0 branch?

**Comment by walterdolce** [comment]
@ncs-alane 

> Can you change the version number to 0.4 and point this pull request to the ncs-alane-0.4.0 branch?

Sure, I can. What about the current branch, though?
0.3.0 will contain misleading documentation...


Also, have you noticed you're missing tags in this repository? The releases published in RubyGems don't map to the ones here. This is also misleading. Please see below.
screen shot 2016-11-20 at 21 54 46
screen shot 2016-11-20 at 21 59 05

**Comment by ncs-alane** [comment]
The only important branch is master; all others are just used for development and intended to be discarded once they are merged.  

I don't recall actively creating releases on GitHub, but there should be a tag on the master branch for each version released on RubyGems.

**Comment by walterdolce** [comment]
> I don't recall actively creating releases on GitHub

There's no need to actively create releases. If the repository has tags, when those are pushed are automagically detected.

> but there should be a tag on the master branch for each version released on RubyGems

There isn't. `git tag` gives only:
```
v0.1.0
v0.1.1
v0.1.2
```

**Comment by walterdolce** [comment]
By the way, I can't point this PR to another branch. 
What I would suggest is to merge this PR, tag current `master` to `v0.3.0`. 

In the mean time I will do what you said above and raise another PR against the branch you mentioned. What do you think?

**Comment by ncs-alane** [comment]
Please open the new pull request. Commits to master are reserved for released versions of the gem, and since v0.3.0 has already been released with a copy of the README, making the change will require a new release. I did add the missing tags and releases, though; thanks for pointing that out!

**Comment by walterdolce** [comment]
Ok, thanks for clarifying! PR on its way..

**Pull request closed without merging**
